// 全ダンジョン一括生成(品質刷新v3.1 M7b) — シード表から src/dungeon/maps.gen.ts を自動出力
// 使い方: node scripts/gen_all_maps.mjs
// 醜いフロアが出たら、この表のseedを1つ変えて再実行するだけ(ASCIIの手編集は禁止)。
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { generateFloor } from './gen_floor.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT = join(__dirname, '..', 'src', 'dungeon', 'maps.gen.ts')

// 地域表 — floors=階数(最終階は必ずボスの間)。water=水域を生成する地域。
// seedOverrides: {階idx: シード} — 見た目の手直しはここに1エントリ足すだけ。
const REGION_TABLE = [
  { id: 'yoi_forest', name: '宵の森', tier: 1, floors: 3 },
  { id: 'nureen_no_tsuji', name: '濡れ縁の辻', tier: 1, floors: 4, water: true },
  { id: 'karasu_no_sato', name: '烏の里', tier: 1, floors: 2 },
  { id: 'tourou_kuzure_michi', name: '灯篭崩れ道', tier: 1, floors: 4 },
  { id: 'mushishigure_michi', name: '蟲時雨の径', tier: 1, floors: 3 },
  { id: 'karita_no_bourei', name: '苅田の亡霊', tier: 1, floors: 4 },
  { id: 'yaregasa_douhyou', name: '破れ傘の道標', tier: 1, floors: 3 },
  { id: 'minomushi_no_kairou', name: '蓑虫の廻廊', tier: 1, floors: 4 },
  { id: 'chochin_zaka', name: '提灯坂', tier: 2, floors: 4 },
  { id: 'oboro_bashi', name: '朧橋', tier: 2, floors: 5, water: true },
  { id: 'nurikabe_koji', name: '塗壁小路', tier: 2, floors: 3 },
  { id: 'suzuriishi_no_saka', name: '硯石の坂', tier: 2, floors: 5 },
  { id: 'haikyo_goten', name: '廃墟の御殿', tier: 2, floors: 3 },
  { id: 'kare_numa', name: '涸れ沼の畔', tier: 2, floors: 4, water: true },
  { id: 'rousoku_kashi', name: '蝋燭河岸', tier: 2, floors: 5, water: true },
  { id: 'kagami_ga_fuchi', name: '鏡ヶ淵', tier: 2, floors: 5, water: true },
  { id: 'hoshimukuro_tani', name: '星骸の谷', tier: 3, floors: 5 },
  { id: 'kageboushi_no_oka', name: '影法師の丘', tier: 3, floors: 5 },
  { id: 'kaji_ato', name: '鍛地の跡', tier: 3, floors: 3 },
  { id: 'kottou_zaka', name: '骨董坂', tier: 3, floors: 5 },
  { id: 'hyakki_yakou_no_tsuji', name: '百鬼夜行の辻', tier: 3, floors: 5 },
  { id: 'hakkotsu_bayashi', name: '白骨林', tier: 3, floors: 4 },
  { id: 'tokoyami_no_kairou', name: '常闇の回廊', tier: 3, floors: 5 },
  { id: 'hoshikui_no', name: '星喰い野', tier: 4, floors: 5 },
  { id: 'mouja_machi', name: '亡者町', tier: 4, floors: 5 },
  { id: 'gentou_zentei', name: '玄冬前庭', tier: 4, floors: 5 },
  { id: 'akashi_miyama', name: '灯ノ御山', tier: 4, floors: 6 },
]

const lines = []
lines.push('// ============================================================')
lines.push('// AUTO-GENERATED by scripts/gen_all_maps.mjs — 手編集禁止')
lines.push('// 直したいフロアがあれば gen_all_maps.mjs のシード表を変えて再実行する')
lines.push('// ============================================================')
lines.push("import type { DungeonDef } from './types'")
lines.push('')
lines.push('export const DUNGEONS_GEN: DungeonDef[] = [')

let totalFloors = 0
for (let ri = 0; ri < REGION_TABLE.length; ri++) {
  const region = REGION_TABLE[ri]
  lines.push('  {')
  lines.push(`    regionId: '${region.id}',`)
  lines.push(`    name: '${region.name}',`)
  lines.push('    floors: [')
  for (let fi = 0; fi < region.floors; fi++) {
    const isBoss = fi === region.floors - 1
    const seed = region.seedOverrides?.[fi] ?? (ri + 1) * 1000 + (fi + 1)
    const { ascii, seed: usedSeed } = generateFloor({
      seed,
      boss: isBoss,
      water: !!region.water && !isBoss,
      chests: isBoss ? 1 : 2,
      camps: isBoss ? 0 : 1,
      shrines: isBoss ? 0 : 1,
      monuments: isBoss ? 0 : 1,
    })
    const shades = isBoss ? 4 : Math.min(10, 4 + region.tier + fi)
    lines.push('      {')
    lines.push('        ascii: [')
    for (const row of ascii) lines.push(`          '${row}',`)
    lines.push('        ],')
    lines.push(`        shades: ${shades},`)
    lines.push(`        seed: ${usedSeed},`)
    lines.push('      },')
    totalFloors++
  }
  lines.push('    ],')
  lines.push('  },')
}
lines.push(']')
lines.push('')

writeFileSync(OUT, lines.join('\n'), 'utf8')
console.log(`maps.gen.ts を出力: ${REGION_TABLE.length}地域 / ${totalFloors}フロア`)
